### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by senthilnathann** [vincentbernat/ip_vs_csh#1]
Hi,

Good day . 

I am getting below error during ip_vs_csh compilation time ,

**error: implicit declaration of function ‘ip_vs_iph_inverse’ [-Werror=implicit-function-declaration]
   if (likely(!ip_vs_iph_inverse(iph)))
   ^
cc1: some warnings being treated as errors**

gcc version : gcc version 4.8.5 20150623 (Red Hat 4.8.5-16) (GCC)

Kindly check and do the need full .

Regards,
Senthil

**Comment by vincentbernat** [comment]
Which kernel are you using? 3.10?

**Comment by senthilnathann** [comment]
yes. 3.10.0-693.21.1.el7.x86_64

**Comment by vincentbernat** [comment]
This should be fixed with commit d477c73a8977.
